// this file generate by @ray-js/build-plugin-router.
// do not modify this file!!!
export const thing = {
  themeLocation: 'theme.json',
  window: {
    backgroundColor: '#f2f4f6',
    navigationBarTitleText: '',
    navigationBarBackgroundColor: '#f2f4f6',
    navigationBarTextStyle: 'black',
  },
  pages: [
    'pages/playground/index',
    'pages/home/index',
    'pages/button/index',
    'pages/cell/index',
    'pages/config-provider/index',
    'pages/icon/index',
    'pages/image/index',
    'pages/col/index',
    'pages/popup/index',
    'pages/style/index',
    'pages/toast/index',
    'pages/transition/index',
    'pages/calendar/index',
    'pages/cascader/index',
    'pages/checkbox/index',
    'pages/datetime-picker/index',
    'pages/field/index',
    'pages/picker/index',
    'pages/radio/index',
    'pages/rate/index',
    'pages/search/index',
    'pages/slider/index',
    'pages/stepper/index',
    'pages/switch/index',
    'pages/action-sheet/index',
    'pages/dialog/index',
    'pages/dropdown-menu/index',
    'pages/loading/index',
    'pages/notify/index',
    'pages/overlay/index',
    'pages/swipe-cell/index',
    'pages/circle/index',
    'pages/collapse/index',
    'pages/count-down/index',
    'pages/divider/index',
    'pages/empty/index',
    'pages/notice-bar/index',
    'pages/skeleton/index',
    'pages/tag/index',
    'pages/steps/index',
    'pages/sticky/index',
    'pages/tree-select/index',
    'pages/grid/index',
    'pages/index-bar/index',
    'pages/sidebar/index',
    'pages/nav-bar/index',
    'pages/tab/index',
    'pages/tabbar/index',
    'pages/battery/index',
    'pages/custom-keyboard/index',
  ],
};
