name: Merge Check Build
on: 
  pull_request:
    branches:
      - main
      - release/*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - run: echo '安装依赖'
      - run: yarn install --frozen-lockfile
      - run: echo '检查源码编译是否正常'
      - run: yarn run build
      