name: Sync README & ConfigType

on: [push]
  
jobs:
  sync_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'

    - name: Configure Git Identity
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Clone miniapp
      run: |
        git clone -b ${{ github.ref_name }} https://github.com/Tuya-Community/miniapp-smart-ui.git
      env:
        GITHUB_TOKEN: ${{ secrets.MINIAPP_TOKEN }}
    - name: Sync Code
      run: |
        yarn syncMiniappData
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}